# Generated by Django 3.2.10 on 2021-12-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custome_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='custuser',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
