# Generated by Django 3.2.10 on 2021-12-24 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custome_user', '0002_auto_20211224_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='custuser',
            name='password1',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='custuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
