# Generated by Django 3.2.10 on 2021-12-24 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custome_user', '0004_student_model_teacher_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_model',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher_model',
            name='user',
        ),
    ]
